#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, unlinkSync, readdirSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import * as p from "@clack/prompts";

const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);
const begin = "<!-- t3code-rtl:begin -->", end = "<!-- t3code-rtl:end -->";
const rel = "apps/server/dist/client/index.html";
const label = "io.github.farhadeidi.t3code-rtl-disable-auto-update";
const appDirs = () => process.env.T3CODE_APP_DIRS?.split("\n").filter(Boolean) ?? (process.platform === "darwin" ? requireGlob("/Applications/T3 Code*.app") : ["/opt/t3code-bin", "/opt/t3code-nightly-bin"]);
function requireGlob(pattern: string) { const { dir, base } = { dir: dirname(pattern), base: basename(pattern).replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace("\\*", ".*") }; try { return readdirSync(dir).filter((x) => new RegExp(`^${base}$`).test(x)).map((x)=>join(dir,x)).sort(); } catch { return []; } }
const configPath = () => process.platform === "darwin" ? join(process.env.HOME!, "Library", "Application Support", "t3code-rtl", "config.json") : join(process.env.XDG_CONFIG_HOME ?? join(process.env.HOME!, ".config"), "t3code-rtl", "config.json");
function config(): Record<string, unknown> { try { return JSON.parse(readFileSync(configPath(), "utf8")); } catch { return {}; } }
function save(value: Record<string, unknown>) { mkdirSync(dirname(configPath()), { recursive: true }); writeFileSync(configPath(), JSON.stringify(value, null, 2) + "\n"); }
function resource(app:string) { for (const middle of ["resources", "Contents/Resources"]) { const r=join(app,middle); if (existsSync(join(r,"app.asar")) || existsSync(join(r,"app.asar.unpacked",rel))) return r; } }
function support(name:string) { for (const path of [join(root,name), join(root,"fonts",name)]) if (existsSync(path)) return path; throw new Error(`${name} is missing`); }
function payload() { let js=readFileSync(support("rtl.js"),"utf8"); const font=readFileSync(support("AradNLVF.woff2")).toString("base64"); return js.replace("__T3CODE_ARAD_FONT__",`data:font/woff2;base64,${font}`); }
function inject(html:string, js:string) { const old=new RegExp(`[ \\t]*${begin.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\n?`,"g"); const clean=html.replace(old,""); if (!clean.includes("</body>")) throw Error("index.html has no </body>"); return clean.replace("</body>",`${begin}\n<script>\n${js}</script>\n${end}\n  </body>`); }
function entry(header:any) { let node=header; for (const part of rel.split("/")) { node=node?.files?.[part]; } return node; }
function integrity(data:Buffer) { const blockSize=4*1024*1024, hash=(x:Buffer)=>createHash("sha256").update(x).digest("hex"); const blocks=[]; for(let i=0;i<data.length;i+=blockSize) blocks.push(hash(data.subarray(i,i+blockSize))); return {algorithm:"SHA256",hash:hash(data),blockSize,blocks}; }
function asarIntegrityEnforced(app:string): boolean | undefined { const sentinel=Buffer.from("dL7pKGdnNz796PbbjQWNKmHXBZaB9tsX"); const framework=join(app,"Contents","Frameworks","Electron Framework.framework","Versions"); const candidates=existsSync(framework) ? readdirSync(framework).map((v)=>join(framework,v,"Electron Framework")) : []; for(const file of candidates) { try { const data=readFileSync(file), at=data.indexOf(sentinel); if(at>=0) return data[at+sentinel.length+2+4]===0x31; } catch {} } return undefined; }
function patchAsar(asar:string, unpacked:string, js:string) { const raw=readFileSync(asar), jsonLen=raw.readUInt32LE(12), header=JSON.parse(raw.subarray(16,16+jsonLen).toString()); const e=entry(header); if(!e) throw Error("client index was not found in app.asar"); const target=join(unpacked,rel); const html=e.unpacked && existsSync(target) ? readFileSync(target,"utf8") : raw.subarray(8+raw.readUInt32LE(4)+Number(e.offset),8+raw.readUInt32LE(4)+Number(e.offset)+Number(e.size)).toString(); const patched=Buffer.from(inject(html,js)); mkdirSync(dirname(target),{recursive:true}); writeFileSync(target,patched); chmodSync(target,0o644); delete e.offset; e.size=patched.length; e.unpacked=true; e.integrity=integrity(patched); const encoded=Buffer.from(JSON.stringify(header)); if(encoded.length>jsonLen) throw Error("patched ASAR header would grow"); encoded.copy(raw,16); raw.fill(0x20,16+encoded.length,16+jsonLen); writeFileSync(asar,raw); }
function patch() { const js=payload(); let count=0; for(const app of appDirs()) { const r=resource(app); if(!r) continue; const plain=join(r,"app.asar.unpacked",rel); try { if(existsSync(plain)) writeFileSync(plain,inject(readFileSync(plain,"utf8"),js)); else { const enforced=asarIntegrityEnforced(app); if(enforced!==false && !process.env.T3CODE_RTL_FORCE) throw Error(`ASAR integrity validation is ${enforced ? "enabled" : "unknown"}; refusing to patch`); patchAsar(join(r,"app.asar"),join(r,"app.asar.unpacked"),js); } count++; p.log.success(`Patched ${basename(app)}`); } catch(e) { p.log.error(`${basename(app)}: ${(e as Error).message}`); } } if(!count) throw Error("No T3 Code installation was patched."); }
function agent() { return join(process.env.HOME!,"Library","LaunchAgents",`${label}.plist`); }
function launch(args:string[], quiet=false) { return spawnSync("launchctl",args,{stdio:quiet?"ignore":"inherit"}).status===0; }
function setMode(mode:"managed"|"native") { const c=config(); if(process.platform!=="darwin") { save({...c,updateMode:"native"}); return; } launch(["bootout",`gui/${process.getuid?.()}/${label}`],true); if(mode==="managed") { mkdirSync(dirname(agent()),{recursive:true}); writeFileSync(agent(),`<?xml version="1.0"?><plist version="1.0"><dict><key>Label</key><string>${label}</string><key>ProgramArguments</key><array><string>/bin/launchctl</string><string>setenv</string><string>T3CODE_DISABLE_AUTO_UPDATE</string><string>true</string></array><key>RunAtLoad</key><true/></dict></plist>`); launch(["bootstrap",`gui/${process.getuid?.()}`,agent()]); launch(["setenv","T3CODE_DISABLE_AUTO_UPDATE","true"]); save({...c,updateMode:mode,managedByPatch:true}); } else { try{unlinkSync(agent());}catch{} if(c.managedByPatch) launch(["unsetenv","T3CODE_DISABLE_AUTO_UPDATE"],true); save({...c,updateMode:mode,managedByPatch:false}); } }
async function approve(message:string) { const answer=await p.confirm({message}); if(p.isCancel(answer) || !answer) { p.cancel("No changes were made."); return false; } return true; }
async function setup() { p.intro("T3 Code RTL Patch"); const found=appDirs().filter(existsSync); if(!found.length) { p.outro("T3 Code was not found."); return; } p.log.success(`Found ${found.map((path) => basename(path)).join(", ")}`); const mode = process.platform === "darwin" ? await p.select({message:"How should updates work?",options:[{value:"managed",label:"Homebrew + automatic re-patch",hint:"recommended"},{value:"native",label:"Keep T3 Code automatic updates",hint:"patch manually afterward"}]}) : "native"; if(p.isCancel(mode)) return p.cancel("Cancelled."); if(!await approve(`This will configure ${mode} updates and modify ${found.length} T3 Code app bundle(s). Continue?`)) return; setMode(mode as "managed"|"native"); patch(); p.outro("Ready."); }
function status(){const apps=appDirs().filter(existsSync); console.log(`T3 Code: ${apps.length?apps.join(", "):"not found"}`); console.log(`Update mode: ${config().updateMode??"not configured"}`);}
async function update(){ if(process.platform!=="darwin") throw Error("Update T3 Code through your package manager, then run: t3code-rtl patch"); if(!await approve("This will update T3 Code with Homebrew and modify its app bundle. Continue?")) return; execFileSync("brew",["upgrade","--cask","--greedy","t3-code"],{stdio:"inherit"}); patch(); }
async function interactive(){ if(!config().updateMode) return setup(); p.intro("T3 Code RTL Patch"); const a=await p.select({message:"What do you want to do?",options:[{value:"patch",label:"Apply patch now"},{value:"status",label:"Check status"},{value:"setup",label:"Change update strategy"},...(process.platform==="darwin"?[{value:"update",label:"Update T3 Code now"}]:[])]}); if(p.isCancel(a)) return p.cancel("Cancelled."); if(a==="patch") { if(await approve("This will modify the T3 Code app bundle. Continue?")) patch(); } else if(a==="status") status(); else if(a==="setup") await setup(); else await update(); p.outro("Done."); }
async function main(){ const command=process.argv[2]; try { if(!command) await interactive(); else if(command==="setup") await setup(); else if(command==="patch") { if(await approve("This will modify the T3 Code app bundle. Continue?")) patch(); } else if(command==="status"||command==="doctor") status(); else if(command==="update") await update(); else throw Error("Usage: t3code-rtl [setup|patch|status|doctor|update]"); } catch(e){ p.log.error((e as Error).message); process.exitCode=1; } }
void main();
